[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.11.0"

[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gobuffalo/suite"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/unrolled/secure"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/gobuffalo/x"
